# Generated by Django 4.1.2 on 2022-10-30 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='captions',
            new_name='caption',
        ),
    ]
