# Generated by Django 4.1.2 on 2022-11-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_followerscount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='selflike',
            field=models.IntegerField(default=0),
        ),
    ]
